// Generated by CoffeeScript 1.9.3

/*
This is separate React jsx-based on CoffeeScript with backticks for Clinch processor
 */

(function() {
  var clinch_coffee, clinch_jsx, extension, processor;

  clinch_coffee = require('clinch.coffee');

  clinch_jsx = require('clinch.jsx');

  extension = '.csbx';

  processor = function(data, filename, cb) {
    return clinch_coffee.processor(data, filename, function(err, decaffeinated) {
      if (err != null) {
        return cb(err);
      }
      return clinch_jsx.processor(decaffeinated, filename, function(err, content) {
        if (err != null) {
          return cb(err);
        }
        return cb(null, content, true);
      });
    });
  };

  module.exports = {
    extension: extension,
    processor: processor
  };

}).call(this);
